<?php

declare(strict_types=1);

return [
    'assets' => [
        'hero_exterior' => [
            'seed_key'  => 'homepage:hero-exterior:v1',
            'filename'  => 'Goetz-Legal-Exterior-1.png',
            'sha256'    => '8c3cb4f2f78d9267304c9ee2dfc6e33054f038b9ebd20caef0441246c2d3f5ce',
            'mime'      => 'image/png',
            'width'     => 3072,
            'height'    => 3072,
            'title'     => 'Goetz Legal exterior',
            'alt'       => 'Goetz Legal exterior',
        ],
        'welcome_left' => [
            'seed_key'  => 'homepage:welcome-left:v1',
            'filename'  => 'PXL_20220818_164549897_2.jpg',
            'sha256'    => 'e7710d826d8a5f0dc1e7b53b12eef3d9066530cb671724611d2dd1ed66c1ff6f',
            'mime'      => 'image/jpeg',
            'width'     => 1194,
            'height'    => 1138,
            'title'     => 'James L. Goetz recognition plaque',
            'alt'       => 'James L. Goetz recognition plaque',
        ],
        'welcome_right' => [
            'seed_key'  => 'homepage:welcome-right:v1',
            'filename'  => 'Sue.jpg',
            'sha256'    => 'd1fa1baeffababe91d23313bf85f79c4fcd0864aa93c22ac2a7bb5b75d69b334',
            'mime'      => 'image/jpeg',
            'width'     => 377,
            'height'    => 500,
            'title'     => 'Goetz Legal office library photo',
            'alt'       => 'Goetz Legal office library photo',
        ],
        'scale_icon' => [
            'seed_key'  => 'site:scale-icon:v1',
            'filename'  => 'law-scale-icon-purple.png',
            'sha256'    => '53eade44aed3bacbb4bc00665c43811395ba91a1f1699f338c9e0a07a017cfd0',
            'mime'      => 'image/png',
            'width'     => 40,
            'height'    => 39,
            'title'     => 'Purple scales of justice icon',
            'alt'       => '',
        ],
        'practice_bg' => [
            'seed_key'  => 'homepage:practice-background:v1',
            'filename'  => 'firm-bg.jpg',
            'sha256'    => '4a96ab8dfde5af0b61a13faa5fd49a29f6f167351d51d2d2461f428208e1c561',
            'mime'      => 'image/jpeg',
            'width'     => 1350,
            'height'    => 900,
            'title'     => 'Law office books and desk',
            'alt'       => 'Law office books and desk',
        ],
        'james_card' => [
            'seed_key'  => 'homepage:james-card:v1',
            'filename'  => 'JAMES-L.jpg',
            'sha256'    => '98c56bcab4a5824d6771b29b2ae4547f1097a1a78a788f4c94cc6eff5832e331',
            'mime'      => 'image/jpeg',
            'width'     => 1200,
            'height'    => 660,
            'title'     => 'James L. Goetz',
            'alt'       => 'James L. Goetz',
        ],
        'gregory_card' => [
            'seed_key'  => 'homepage:gregory-card:v1',
            'filename'  => 'Greg-Website-Portrait-6.jpg',
            'sha256'    => '94b15c45d6ef4a152ed45935a06a52671cdff17934da1d7a9e03fdad94092755',
            'mime'      => 'image/jpeg',
            'width'     => 1200,
            'height'    => 660,
            'title'     => 'Gregory W. Goetz',
            'alt'       => 'Gregory W. Goetz',
        ],
        'cta_background' => [
            'seed_key'  => 'homepage:cta-background:v1',
            'filename'  => 'law-updates-bg.jpg',
            'sha256'    => '65dc5280c5d08135334fc3a02a9b66616bd517f265a4a2fee4c8904e7f5cb11f',
            'mime'      => 'image/jpeg',
            'width'     => 2304,
            'height'    => 1280,
            'title'     => 'Law updates gavel background',
            'alt'       => '',
        ],
        'header_logo' => [
            'seed_key'  => 'site:header-logo:v1',
            'filename'  => 'GoetzLogo.png',
            'sha256'    => 'a2c78c7088101503dafc5c678f2658557e91b061639a4b3ddc309651a74e10ec',
            'mime'      => 'image/png',
            'width'     => 300,
            'height'    => 92,
            'title'     => 'Goetz & Goetz logo',
            'alt'       => 'Goetz & Goetz',
        ],
        'footer_logo' => [
            'seed_key'  => 'site:footer-logo:v1',
            'filename'  => 'Goetz-footer-logo.png',
            'sha256'    => '641d06bb5715d2935a6d84d7733a833aabc00a9fc74f335774c764104adb4b01',
            'mime'      => 'image/png',
            'width'     => 274,
            'height'    => 86,
            'title'     => 'Goetz & Goetz footer logo',
            'alt'       => 'Goetz & Goetz',
        ],
        'social_image' => [
            'seed_key'  => 'site:social-image:v1',
            'filename'  => 'goetz-social-1200x630.jpg',
            'sha256'    => '5dc3f7d979c25a2fb269e86b81cd52fc8ec0a2a9049cee48baf6e24a41b4e7f0',
            'mime'      => 'image/jpeg',
            'width'     => 1200,
            'height'    => 630,
            'title'     => 'Goetz & Goetz office exterior',
            'alt'       => 'Goetz & Goetz office exterior',
        ],
    ],
    'menus' => [
        'primary' => [
            'seed_key' => 'homepage:primary-menu:v1',
            'name'     => 'Goetz Primary Menu',
            'items'    => [
                ['label' => 'Home', 'slug' => 'home'],
                ['label' => 'James L. Goetz', 'slug' => 'james-l-goetz'],
                ['label' => 'Gregory W. Goetz', 'slug' => 'gregory-w-goetz'],
                ['label' => 'Staff', 'slug' => 'staff'],
                ['label' => 'Questions', 'slug' => 'questions'],
                ['label' => 'Links', 'slug' => 'links'],
                ['label' => 'Contact', 'slug' => 'contact'],
            ],
        ],
        'footer' => [
            'seed_key' => 'homepage:footer-menu:v1',
            'name'     => 'Goetz Footer Menu',
            'items'    => [
                ['label' => 'Home', 'slug' => 'home'],
                ['label' => 'James L. Goetz', 'slug' => 'james-l-goetz'],
                ['label' => 'Gregory W. Goetz', 'slug' => 'gregory-w-goetz'],
                ['label' => 'Staff', 'slug' => 'staff'],
                ['label' => 'Questions', 'slug' => 'questions'],
                ['label' => 'Links', 'slug' => 'links'],
                ['label' => 'Contact Us', 'slug' => 'contact'],
            ],
        ],
    ],
    'homepage' => [
        'hero' => [
            'eyebrow'     => 'GoetzLegal.com',
            'heading'     => 'A law firm with<br>seasoned trial<br>attorneys <b>in</b><br><b>Fort Myers,<br>Florida.</b>',
            'content'     => 'Goetz & Goetz represents all individuals who need legal advice in regards to corporate, construction, real estate, probate, criminal and bankruptcy matters. Goetz & Goetz has been a legal resource in Fort Myers for over 50 years and has a vast amount of legal experience at your disposal.',
            'image'       => 'hero_exterior',
            'buttonText'  => 'Learn More About Us',
            'buttonUrl'   => '/james-l-goetz/',
            'buttonNewTab'=> false,
        ],
        'welcome' => [
            'leftImage'   => 'welcome_left',
            'rightImage'  => 'welcome_right',
            'heading'     => '<strong>Mr. Goetz welcomes</strong> you to browse this site to learn more about his firm and get information.',
            'contentPrefix'=> 'If you would like to speak with Mr. Goetz, please call',
            'phoneLabel'  => '',
            'phoneUrl'    => '',
            'contentJoin' => 'or contact the firm',
            'onlineLabel' => 'online',
            'onlineUrl'   => '',
        ],
        'practiceAreas' => [
            'heading'        => 'Providing <strong>Legal Advice</strong> in:',
            'backgroundImage'=> 'practice_bg',
            'scaleImage'     => 'scale_icon',
            'items'          => [
                'Corporate',
                'Construction',
                'Real Estate',
                'Probate',
                'Criminal',
                'Bankruptcy',
                'Appeals',
            ],
        ],
        'attorneyGrid' => [
            'heading'   => 'Attorneys',
            'attorneys' => [
                [
                    'name'       => 'James L. Goetz',
                    'bio'        => 'James L. Goetz was born in Erie, Pennsylvania. He grew up in Oil City and Girard, Pennsylvania working on his father’s farm and coal mines until he went to college.',
                    'image'      => 'james_card',
                    'profileUrl' => '/james-l-goetz/',
                ],
                [
                    'name'       => 'Gregory W. Goetz',
                    'bio'        => 'Mr. Gregory W. Goetz was born and raised here in Fort Myers, Florida. He attended Fort Myers High School and then was accepted to University of Florida.',
                    'image'      => 'gregory_card',
                    'profileUrl' => '/gregory-w-goetz/',
                ],
            ],
        ],
        'cta' => [
            'eyebrow'           => 'WE ARE AN EXPERIENCED TEAM',
            'heading'           => 'NEED A LAWYER?',
            'buttonText'        => '',
            'buttonUrl'         => '',
            'backgroundImage'   => 'cta_background',
            'buttonNewTab'      => false,
        ],
    ],
];
